In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd
import numpy as np
data = pd.read_csv("Random_shopping_cart.csv")

data = data.replace({" ": None})
data = data.replace({np.nan: None})
data.head()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,pork,sandwich bags,lunch meat,all- purpose,flour,soda,butter,vegetables,beef,aluminum foil,all- purpose,dinner rolls,shampoo,all- purpose
1,shampoo,hand soap,waffles,vegetables,cheeses,mixes,milk,sandwich bags,laundry detergent,dishwashing liquid/detergent,waffles,individual meals,hand soap,vegetables
2,pork,soap,ice cream,toilet paper,dinner rolls,hand soap,spaghetti sauce,milk,ketchup,sandwich loaves,poultry,toilet paper,ice cream,ketchup
3,juice,lunch meat,soda,toilet paper,all- purpose,None,None,None,None,None,None,None,None,None
4,pasta,tortillas,mixes,hand soap,toilet paper,vegetables,vegetables,paper towels,vegetables,flour,vegetables,pork,poultry,eggs

In [3]:
unique_list = []
for col in data.columns:
    list = data[col].unique()
    for l in list:
        if l not in unique_list:
            unique_list.append(l)
    
print(unique_list)

[' pork', ' shampoo', ' juice', ' pasta', ' toilet paper', ' paper towels', ' poultry', ' coffee/tea', ' ice cream', ' tortillas', ' fruits', ' dinner rolls', ' sandwich bags', ' hand soap', ' laundry detergent', ' dishwashing liquid/detergent', ' vegetables', ' all- purpose', ' sugar', ' sandwich loaves', ' bagels', ' butter', ' eggs', ' mixes', ' cheeses', ' lunch meat', ' milk', ' cereals', ' spaghetti sauce', ' waffles', ' aluminum foil', ' flour', ' yogurt', ' soda', ' ketchup', ' individual meals', ' soap', ' beef', None]

In [4]:
new_df = pd.DataFrame()
for stuff in unique_list:
    new_df[str(stuff).lstrip(" ")] = 0

new_df

Empty DataFrame
Columns: [pork, shampoo, juice, pasta, toilet paper, paper towels, poultry, coffee/tea, ice cream, tortillas, fruits, dinner rolls, sandwich bags, hand soap, laundry detergent, dishwashing liquid/detergent, vegetables, all- purpose, sugar, sandwich loaves, bagels, butter, eggs, mixes, cheeses, lunch meat, milk, cereals, spaghetti sauce, waffles, aluminum foil, flour, yogurt, soda, ketchup, individual meals, soap, beef, None]
Index: []

[0 rows x 39 columns]

In [5]:
data_matrix = np.matrix(data)
for i in range(len(data_matrix)):
    row = np.array(data_matrix[i])[0]
    temp = {}
    for col in new_df.columns:
        temp[col] = [0]  
    for k in range(len(row)):
        for col in new_df.columns:
            if(col ==   str(row[k]).lstrip(" ")):
                temp[col] = [1]
    new_row = pd.DataFrame(temp)
    new_df = pd.concat([new_df, new_row], ignore_index=True)
new_df

,pork,shampoo,juice,pasta,toilet paper,paper towels,poultry,coffee/tea,ice cream,tortillas,...,waffles,aluminum foil,flour,yogurt,soda,ketchup,individual meals,soap,beef,None
0,1,1,0,0,0,0,0,0,0,0,...,0,1,1,0,1,0,0,0,1,0
1,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
2,1,0,0,0,1,0,1,0,1,0,...,0,0,0,0,0,1,0,1,0,0
3,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
4,1,0,0,1,1,1,1,0,0,1,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,0,1,1,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
1495,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1496,0,1,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,1,0,1,0
1497,0,0,0,0,1,0,1,0,0,0,...,1,0,0,1,0,1,0,1,1,0
1498,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [6]:
index_list =[i for i in range(1,new_df.shape[0]+1)]
new_df.insert(0, 'TID', index_list)
new_df.set_index('TID', inplace=True)
new_df = new_df.drop(["None"], axis=1)
new_df

,pork,shampoo,juice,pasta,toilet paper,paper towels,poultry,coffee/tea,ice cream,tortillas,...,spaghetti sauce,waffles,aluminum foil,flour,yogurt,soda,ketchup,individual meals,soap,beef
TID,,,,,,,,,,,,,,,,,,,,,
1,1,1,0,0,0,0,0,0,0,0,...,0,0,1,1,0,1,0,0,0,1
2,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
3,1,0,0,0,1,0,1,0,1,0,...,1,0,0,0,0,0,1,0,1,0
4,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
5,1,0,0,1,1,1,1,0,0,1,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,0,1,1,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
1496,0,0,0,1,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
1497,0,1,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,1,0,1
1498,0,0,0,0,1,0,1,0,0,0,...,1,1,0,0,1,0,1,0,1,1
1499,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
new_df.to_csv("Cleaned_Random_shopping_cart.csv")